#!/usr/bin/env python3
"""
EchoSphere — NISAR HDF5 processing pipeline
===========================================
Team THEIA · NASA Space Apps Challenge 2026 · "Dancing with the SARs"

What this script does
---------------------
1. Scans  data/raw/  for NISAR HDF5 files (*.h5) that YOU downloaded from NASA / ASF.
2. Opens each file, discovers the science datasets and the geolocation grids.
3. Reads real metadata (product type, acquisition time, granule id, maturity...).
4. Converts / reprojects / downsamples the data for the web.
5. Writes small PNG overlays (< 1 MB each) into  data/processed/.
6. For two or more compatible GCOV observations of the same place it computes
   real backscatter change statistics and an *approximate* open-water mask.
7. Writes  data/manifest.js , which the website loads with a normal <script> tag.

Nothing here is invented: every number written to the manifest is computed from
the files in data/raw/. If data/raw/ is empty, an empty manifest is written and
the website automatically falls back to clearly-labelled DEMO data.

Heavy libraries (h5py, numpy, rasterio, pyproj, Pillow) are imported only when
there is at least one file to process, so an empty run works on any Python 3.10+.

Usage:
    python process_nisar.py
"""

from __future__ import annotations

import base64
import datetime as _dt
import json
import math
import sys
import traceback
from pathlib import Path

# --------------------------------------------------------------------------
# Paths and processing constants (all of them are reported in the manifest)
# --------------------------------------------------------------------------
ROOT = Path(__file__).resolve().parent
RAW_DIR = ROOT / "data" / "raw"
OUT_DIR = ROOT / "data" / "processed"
MANIFEST_PATH = ROOT / "data" / "manifest.js"

MAX_PNG_BYTES = 1_000_000        # hard limit for every generated PNG (< 1 MB)
READ_MAX_DIM = 4096              # strided read: never pull more than ~4096 px per axis into memory
OVERLAY_MAX_DIM = 1024           # longest side of a web overlay
GRID_MAX_DIM = 200               # longest side of the small grid embedded in the manifest
DEFAULT_WATER_THRESHOLD_DB = -18.0   # exploratory open-water threshold (NOT validated)
CHANGE_THRESHOLD_DB = 3.0        # |Δσ| at or above this counts as "changed"
HIST_EDGES = list(range(-15, 16))    # histogram of Δ backscatter, 1 dB bins from -15 to +15
WATER_CURVE = list(range(-26, -9))   # thresholds for the precomputed open-water curve
DB_GRID_RANGE = (-35.0, 5.0)     # quantisation range for embedded backscatter grids
BANDS = ("LSAR", "SSAR")
GCOV_TERMS = ("HHHH", "VVVV", "HVHV", "VHVH")   # preferred backscatter terms, in order


class UnsupportedFile(Exception):
    """Raised when a file cannot be processed. Carries what we found vs. expected."""

    def __init__(self, message, found=None, expected=None):
        super().__init__(message)
        self.found = found or []
        self.expected = expected or []


# ==========================================================================
# Small helpers
# ==========================================================================
def log(msg=""):
    print(msg, flush=True)


def decode(value):
    """HDF5 strings often arrive as bytes or 1-element numpy arrays. Make them plain Python."""
    try:
        import numpy as np
        if isinstance(value, np.ndarray):
            if value.size == 1:
                value = value.reshape(-1)[0]
            else:
                return [decode(v) for v in value.tolist()]
        if isinstance(value, np.generic):
            value = value.item()
    except ImportError:
        pass
    if isinstance(value, bytes):
        return value.decode("utf-8", errors="replace").strip()
    if isinstance(value, str):
        return value.strip()
    return value


def round_or_none(x, nd=3):
    if x is None:
        return None
    x = float(x)
    if math.isnan(x) or math.isinf(x):
        return None
    return round(x, nd)


def write_manifest(records, info):
    """Write data/manifest.js as plain JavaScript (works when index.html is opened via file://)."""
    MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)
    body = json.dumps(records, indent=2, ensure_ascii=False)
    text = (
        "// AUTO-GENERATED by process_nisar.py — do not edit by hand.\n"
        "// Contains ONLY records computed from real NISAR HDF5 files found in data/raw/.\n"
        "// An empty array means no real files were processed; the site then shows DEMO data.\n"
        f"const NISAR_MANIFEST = {body};\n\n"
        f"const NISAR_MANIFEST_INFO = {json.dumps(info, indent=2, ensure_ascii=False)};\n"
    )
    MANIFEST_PATH.write_text(text, encoding="utf-8")


# ==========================================================================
# 1. Opening HDF5 and discovering datasets
# ==========================================================================
# An HDF5 file is like a folder tree: "groups" are folders and "datasets" are
# arrays. NISAR products put the science layers under /science/<band>/<PRODUCT>/
# and the descriptive metadata under /science/<band>/identification/.

def list_datasets(h5):
    """Return [(path, shape, dtype)] for every dataset in the file."""
    import h5py
    found = []

    def visit(name, obj):
        if isinstance(obj, h5py.Dataset):
            found.append((name, obj.shape, str(obj.dtype)))

    h5.visititems(visit)
    return found


def detect_product(h5):
    """Find which band (LSAR/SSAR) and product (GCOV/GUNW/GOFF) the file contains."""
    for band in BANDS:
        ident = f"science/{band}/identification"
        declared = None
        if ident in h5 and "productType" in h5[ident]:
            declared = decode(h5[ident]["productType"][()])
        for product in ("GCOV", "GUNW", "GOFF"):
            if f"science/{band}/{product}" in h5:
                return band, product, declared
        if declared:
            return band, str(declared).upper(), declared
    return None, None, None


def read_identification(h5, band):
    """Read every scalar in the identification group as real metadata."""
    meta = {}
    ident = f"science/{band}/identification"
    if ident not in h5:
        return meta
    for key, obj in h5[ident].items():
        try:
            if obj.shape in ((), (1,)):
                meta[key] = decode(obj[()])
        except (TypeError, AttributeError, OSError):
            continue  # compound / unusual objects are simply not needed here
    return meta


def find_named(h5, root, name):
    """Return every dataset path under `root` whose last component equals `name`."""
    import h5py
    hits = []
    if root not in h5:
        return hits

    def visit(sub, obj):
        if isinstance(obj, h5py.Dataset) and sub.split("/")[-1] == name:
            hits.append(f"{root}/{sub}")

    h5[root].visititems(visit)
    return sorted(hits)


def walk_up(h5, ds_path, name):
    """Look for a sibling dataset `name` in the dataset's group, then in each parent group."""
    parts = ds_path.split("/")[:-1]
    while parts:
        candidate = "/".join(parts + [name])
        if candidate in h5:
            return candidate
        parts.pop()
    return None


# ==========================================================================
# 2. Geolocation
# ==========================================================================
# NISAR L2 products (GCOV, GUNW, GOFF) are already on a map grid. Each layer has
# 1-D "xCoordinates" and "yCoordinates" (pixel centres, in metres for UTM or
# degrees for EPSG:4326) and a "projection" dataset whose attributes hold the
# EPSG code. From those we build an affine transform: pixel (row, col) -> map x/y.

def read_epsg(h5, ds_path):
    proj_path = walk_up(h5, ds_path, "projection")
    if not proj_path:
        return None, None
    ds = h5[proj_path]
    for attr in ("epsg_code", "epsg", "EPSG"):
        if attr in ds.attrs:
            return int(decode(ds.attrs[attr])), f"{proj_path}@{attr}"
    try:
        value = decode(ds[()])
        if isinstance(value, (int, float)) and 1000 < int(value) < 100000:
            return int(value), proj_path
    except (TypeError, ValueError, OSError):
        pass
    return None, proj_path


def read_grid_layer(h5, ds_path):
    """Read a 2-D layer (strided if large) + its georeferencing. Returns a dict."""
    import numpy as np
    from rasterio.transform import Affine

    ds = h5[ds_path]
    if ds.ndim != 2:
        raise UnsupportedFile(f"{ds_path} is not 2-D", [f"{ds_path} shape={ds.shape}"], ["2-D raster layer"])

    xpath = walk_up(h5, ds_path, "xCoordinates")
    ypath = walk_up(h5, ds_path, "yCoordinates")
    epsg, epsg_src = read_epsg(h5, ds_path)
    missing = [n for n, v in (("xCoordinates", xpath), ("yCoordinates", ypath), ("projection EPSG code", epsg)) if not v]
    if missing:
        raise UnsupportedFile(
            f"geolocation incomplete for {ds_path}",
            found=[f"xCoordinates: {xpath}", f"yCoordinates: {ypath}", f"projection: {epsg_src}"],
            expected=[f"{m} next to {ds_path} or in a parent group" for m in missing],
        )

    # --- Downsampling on read -------------------------------------------------
    # A full NISAR frame can be tens of thousands of pixels wide. Reading every
    # `step`-th pixel keeps memory reasonable; the later reprojection uses
    # *average* resampling to smooth the result onto the web grid.
    rows, cols = ds.shape
    step = max(1, math.ceil(max(rows, cols) / READ_MAX_DIM))
    data = ds[::step, ::step].astype("float32")
    x = h5[xpath][::step].astype("float64")
    y = h5[ypath][::step].astype("float64")
    if len(x) < 2 or len(y) < 2 or len(x) != data.shape[1] or len(y) != data.shape[0]:
        raise UnsupportedFile(
            "coordinate arrays do not match the raster",
            found=[f"data {data.shape}", f"x {len(x)}", f"y {len(y)}"],
            expected=["len(x) == columns and len(y) == rows"],
        )

    # --- No-data handling ------------------------------------------------------
    fill = ds.attrs.get("_FillValue")
    if fill is not None:
        fill = decode(fill)
        if isinstance(fill, (int, float)) and not math.isnan(float(fill)):
            data[data == fill] = np.nan
    data[~np.isfinite(data)] = np.nan

    dx = x[1] - x[0]
    dy = y[1] - y[0]
    # Coordinates are pixel centres; the transform needs the outer corner.
    transform = Affine(dx, 0, x[0] - dx / 2, 0, dy, y[0] - dy / 2)
    units = decode(ds.attrs.get("units")) if "units" in ds.attrs else None
    return {
        "data": data, "transform": transform, "epsg": epsg, "path": ds_path,
        "nativeShape": [int(rows), int(cols)], "readStep": step,
        "nativeSpacing": [round(abs(float(h5[xpath][1] - h5[xpath][0])), 4),
                          round(abs(float(h5[ypath][1] - h5[ypath][0])), 4)],
        "units": units, "fill": fill,
    }


def web_grid_for(layers, max_dim):
    """Common Web-Mercator (EPSG:3857) grid covering all `layers`.

    Leaflet displays maps in Web Mercator and stretches an image overlay linearly
    between its corners, so rendering overlays on an EPSG:3857 grid makes them line
    up correctly with the basemap."""
    from rasterio.transform import Affine, array_bounds
    from rasterio.warp import transform_bounds

    boxes = []
    for L in layers:
        h, w = L["data"].shape
        left, bottom, right, top = array_bounds(h, w, L["transform"])
        boxes.append(transform_bounds(f"EPSG:{L['epsg']}", "EPSG:3857", left, bottom, right, top, densify_pts=21))
    left = min(b[0] for b in boxes); bottom = min(b[1] for b in boxes)
    right = max(b[2] for b in boxes); top = max(b[3] for b in boxes)
    res = max(right - left, top - bottom) / max_dim
    width = max(2, int(math.ceil((right - left) / res)))
    height = max(2, int(math.ceil((top - bottom) / res)))
    return {"transform": Affine(res, 0, left, 0, -res, top), "width": width, "height": height,
            "bounds3857": (left, bottom, right, top), "res": res}


def reproject_to(layer, grid, values=None):
    """Reproject a layer (or replacement `values` on the same geometry) onto a web grid."""
    import numpy as np
    from rasterio.crs import CRS
    from rasterio.warp import Resampling, reproject

    src = layer["data"] if values is None else values
    dst = np.full((grid["height"], grid["width"]), np.nan, dtype="float32")
    reproject(
        source=src, destination=dst,
        src_transform=layer["transform"], src_crs=CRS.from_epsg(layer["epsg"]),
        dst_transform=grid["transform"], dst_crs=CRS.from_epsg(3857),
        src_nodata=np.nan, dst_nodata=np.nan, resampling=Resampling.average,
    )
    return dst


def latlon_bounds(grid):
    """Leaflet bounds [[south, west], [north, east]] of a 3857 grid."""
    from pyproj import Transformer
    t = Transformer.from_crs("EPSG:3857", "EPSG:4326", always_xy=True)
    left, bottom, right, top = grid["bounds3857"]
    west, south = t.transform(left, bottom)
    east, north = t.transform(right, top)
    return [[round(south, 6), round(west, 6)], [round(north, 6), round(east, 6)]]


def pixel_area_km2(grid, bounds):
    """Approximate ground area of one web-grid pixel (Mercator scale corrected at mid-latitude)."""
    lat = (bounds[0][0] + bounds[1][0]) / 2
    side_m = grid["res"] * math.cos(math.radians(lat))
    return side_m * side_m / 1e6


# ==========================================================================
# 3. Colour maps and PNG writing (with the < 1 MB guarantee)
# ==========================================================================
def ramp(values, vmin, vmax, stops):
    """Map values to RGBA using linear colour stops [(pos 0..1, (r,g,b)), ...]. NaN -> transparent."""
    import numpy as np
    t = np.nan_to_num(np.clip((values - vmin) / (vmax - vmin), 0, 1))   # NaN pixels become transparent below
    rgba = np.zeros(values.shape + (4,), dtype="uint8")
    pos = np.array([s[0] for s in stops])
    for c in range(3):
        rgba[..., c] = np.interp(t, pos, [s[1][c] for s in stops]).astype("uint8")
    rgba[..., 3] = np.where(np.isfinite(values), 235, 0)
    return rgba


GRAY = [(0, (8, 12, 20)), (1, (235, 240, 250))]
DIVERGING = [(0, (33, 102, 172)), (0.5, (245, 245, 245)), (1, (178, 24, 43))]   # blue = decrease, red = increase
MAGNITUDE = [(0, (13, 8, 135)), (0.5, (204, 71, 120)), (1, (240, 249, 33))]


def save_png(rgba, path):
    """Save an RGBA overlay and guarantee it is below MAX_PNG_BYTES.

    Strategy: optimised PNG → palette-quantised PNG (lower 'quality') → shrink
    dimensions by 25% and retry. Fails loudly if still too large."""
    from PIL import Image
    img = Image.fromarray(rgba, "RGBA")
    for attempt in range(8):
        img.save(path, optimize=True)
        if path.stat().st_size < MAX_PNG_BYTES:
            return path.stat().st_size, img.size
        img.quantize(colors=128, method=Image.Quantize.FASTOCTREE).save(path, optimize=True)
        if path.stat().st_size < MAX_PNG_BYTES:
            return path.stat().st_size, img.size
        w, h = img.size
        img = img.resize((max(1, int(w * 0.75)), max(1, int(h * 0.75))), Image.Resampling.NEAREST)
    path.unlink(missing_ok=True)
    raise UnsupportedFile(f"could not bring {path.name} below {MAX_PNG_BYTES} bytes", [], ["PNG < 1 MB"])


def encode_grid(values, vmin, vmax):
    """Quantise a small float grid to uint8 (255 = no data) and base64 it for the manifest.

    The browser cannot read pixels from local PNGs (file:// security), so the
    exploratory threshold slider works on this small embedded grid instead."""
    import numpy as np
    q = np.full(values.shape, 255, dtype="uint8")
    ok = np.isfinite(values)
    q[ok] = np.clip(np.round((values[ok] - vmin) / (vmax - vmin) * 254), 0, 254).astype("uint8")
    return {"w": int(values.shape[1]), "h": int(values.shape[0]), "min": vmin, "max": vmax,
            "nodata": 255, "b64": base64.b64encode(q.tobytes()).decode("ascii")}


# ==========================================================================
# 4. Per-product readers
# ==========================================================================
def read_gcov(h5, band, meta):
    """GCOV = geocoded covariance. The diagonal terms (e.g. HHHH) are LINEAR backscatter power."""
    root = f"science/{band}/GCOV/grids"
    candidates = []
    for freq in ("frequencyA", "frequencyB"):
        for term in GCOV_TERMS:
            p = f"{root}/{freq}/{term}"
            if p in h5:
                candidates.append((p, freq, term))
    if not candidates:
        raise UnsupportedFile("no GCOV backscatter term found",
                              found=[p for p, *_ in list_datasets(h5) if "/GCOV/" in p][:15],
                              expected=[f"{root}/frequencyA/{t}" for t in GCOV_TERMS])
    path, freq, term = candidates[0]
    layer = read_grid_layer(h5, path)
    import numpy as np
    layer["data"][layer["data"] <= 0] = np.nan   # log10 of <= 0 is undefined → no data
    # NISAR GCOV ships a per-pixel validity "mask" next to the covariance terms:
    # 0 = invalid / outside the swath, 255 = fill; other values mark valid samples.
    mpath = f"{root}/{freq}/mask"
    if mpath in h5 and h5[mpath].shape == h5[path].shape:
        step = layer["readStep"]
        m = h5[mpath][::step, ::step]
        bad = (m == 0) | (m == 255)
        layer["data"][bad] = np.nan
        layer["maskApplied"] = f"/{mpath}: {int(bad.sum())} of {bad.size} pixels invalid (0 or 255)"
    else:
        layer["maskApplied"] = None
    layer.update({"frequency": freq, "term": term})
    return layer


def read_gunw(h5, band, meta):
    """GUNW = geocoded unwrapped interferogram. Unwrapped phase (radians) ∝ line-of-sight motion."""
    root = f"science/{band}/GUNW/grids"
    hits = find_named(h5, root, "unwrappedPhase")
    if not hits:
        raise UnsupportedFile("no unwrappedPhase layer in GUNW",
                              found=[p for p, *_ in list_datasets(h5) if "/GUNW/" in p][:15],
                              expected=[f"{root}/frequencyA/unwrappedInterferogram/<pol>/unwrappedPhase"])
    layer = read_grid_layer(h5, hits[0])
    # Wavelength lets us convert phase to line-of-sight displacement: d = -λ·φ / (4π)
    wavelength = None
    for name in ("centerFrequency", "centerFrequencyA"):
        f = walk_up(h5, hits[0], name) or next(iter(find_named(h5, f"science/{band}", name)), None)
        if f:
            hz = float(decode(h5[f][()]))
            if hz > 0:
                wavelength = 299_792_458.0 / hz
                layer["wavelengthSource"] = f
                break
    layer["wavelength"] = wavelength
    return layer


def read_goff(h5, band, meta):
    """GOFF = geocoded pixel offsets: how far features moved between two acquisitions."""
    root = f"science/{band}/GOFF/grids"
    along = find_named(h5, root, "alongTrackOffset")
    rng = find_named(h5, root, "slantRangeOffset")
    pairs = [(a, a.rsplit("/", 1)[0] + "/slantRangeOffset") for a in along
             if a.rsplit("/", 1)[0] + "/slantRangeOffset" in rng]
    if not pairs:
        raise UnsupportedFile("no alongTrackOffset/slantRangeOffset pair in GOFF",
                              found=[p for p, *_ in list_datasets(h5) if "/GOFF/" in p][:15],
                              expected=[f"{root}/frequencyA/pixelOffsets/<pol>/layer1/alongTrackOffset (+ slantRangeOffset)"])
    a_path, r_path = pairs[0]
    a = read_grid_layer(h5, a_path)
    r = read_grid_layer(h5, r_path)
    import numpy as np
    a["along"] = a["data"]
    a["range"] = r["data"]
    a["data"] = np.hypot(a["data"], r["data"])   # magnitude of the offset vector (radar geometry)
    a["rangePath"] = r_path
    return a


READERS = {"GCOV": read_gcov, "GUNW": read_gunw, "GOFF": read_goff}


def acquisition_info(meta, product):
    """Pick real acquisition times from identification metadata."""
    def first(*keys):
        for k in keys:
            if meta.get(k):
                return str(meta[k]), k
        return None, None

    if product == "GCOV":
        start, key = first("zeroDopplerStartTime", "referenceZeroDopplerStartTime")
        return {"datetime": start, "dateSource": key}
    ref, rkey = first("referenceZeroDopplerStartTime")
    sec, skey = first("secondaryZeroDopplerStartTime")
    return {"datetime": sec or ref, "dateSource": skey or rkey, "referenceDatetime": ref, "secondaryDatetime": sec}


def parse_date(text):
    if not text:
        return None
    try:
        return _dt.datetime.fromisoformat(text.replace("Z", "").split(".")[0])
    except ValueError:
        return None


def find_maturity(meta):
    """NISAR maturity/processing descriptors differ between releases. Report what the file says."""
    for key in meta:
        if "maturity" in key.lower():
            return str(meta[key]), key
    for key in ("processingType", "productVersion", "productSpecificationVersion"):
        if meta.get(key):
            return f"{key}: {meta[key]}", key
    return None, None


# ==========================================================================
# 5. Processing one file
# ==========================================================================
def load_file(path):
    import h5py
    with h5py.File(path, "r") as h5:
        band, product, declared = detect_product(h5)
        if product not in READERS:
            datasets = list_datasets(h5)
            raise UnsupportedFile(
                f"unsupported or unrecognised product ({product or 'none detected'})",
                found=[f"{p} {s} {d}" for p, s, d in datasets[:20]] + (["..."] if len(datasets) > 20 else []),
                expected=["/science/LSAR/GCOV", "/science/LSAR/GUNW", "/science/LSAR/GOFF"],
            )
        meta = read_identification(h5, band)
        layer = READERS[product](h5, band, meta)

    acq = acquisition_info(meta, product)
    if not acq["datetime"] or not parse_date(acq["datetime"]):
        raise UnsupportedFile("no readable acquisition time in identification metadata",
                              found=sorted(meta.keys()), expected=["zeroDopplerStartTime or referenceZeroDopplerStartTime"])
    maturity, maturity_key = find_maturity(meta)
    granule = meta.get("granuleId")
    return {
        "file": path.name, "band": band, "product": product, "declaredProductType": declared,
        "meta": meta, "layer": layer, "acq": acq,
        "granule": str(granule) if granule else path.stem,
        "granuleSource": "identification/granuleId" if granule else "file name (granuleId not present in file)",
        "maturity": maturity, "maturitySource": maturity_key and f"identification/{maturity_key}",
    }


def gcov_stats(db, grid, bounds, threshold=DEFAULT_WATER_THRESHOLD_DB):
    import numpy as np
    ok = np.isfinite(db)
    n = int(ok.sum())
    if n == 0:
        return None
    px = pixel_area_km2(grid, bounds)
    water = ok & (db < threshold)
    return {
        "meanBackscatterDb": round_or_none(np.nanmean(db), 2),
        "openWaterPercent": round_or_none(100 * water.sum() / n, 2),
        "openWaterKm2": round_or_none(water.sum() * px, 1),
        "validPixels": n,
        "analyzedAreaKm2": round_or_none(n * px, 1),
        "waterCurve": {"thresholdsDb": WATER_CURVE,
                       "percent": [round_or_none(100 * (ok & (db < t)).sum() / n, 2) for t in WATER_CURVE]},
    }


def process_gcov_group(items, site_id):
    """Put every GCOV observation of one site on a shared grid, then compute change between neighbours."""
    import numpy as np
    items.sort(key=lambda it: parse_date(it["acq"]["datetime"]))
    grid = web_grid_for([it["layer"] for it in items], OVERLAY_MAX_DIM)
    small = web_grid_for([it["layer"] for it in items], GRID_MAX_DIM)
    bounds = latlon_bounds(grid)
    records, prev = [], None
    for idx, it in enumerate(items):
        L = it["layer"]
        # --- dB conversion: σ(dB) = 10·log10(σ_linear). Averaging happens in LINEAR
        #     power during reprojection, and only then do we convert to dB.
        with np.errstate(invalid="ignore", divide="ignore"):
            db = 10 * np.log10(reproject_to(L, grid))
            db_small = 10 * np.log10(reproject_to(L, small))
        rid = f"{site_id}-gcov-{idx + 1}"
        size, dims = save_png(ramp(db, -25, 0, GRAY), OUT_DIR / f"{rid}_backscatter.png")
        water_rgba = np.zeros(db.shape + (4,), dtype="uint8")
        water_rgba[np.isfinite(db) & (db < DEFAULT_WATER_THRESHOLD_DB)] = (0, 200, 255, 220)
        wsize, _ = save_png(water_rgba, OUT_DIR / f"{rid}_water.png")
        stats = gcov_stats(db, grid, bounds)
        if stats is None:
            log(f"  ! {it['file']}: no valid backscatter pixels after reprojection — skipped")
            continue
        rec = base_record(it, rid, site_id, bounds)
        rec.update({
            "overlay": f"data/processed/{rid}_backscatter.png",
            "waterOverlay": f"data/processed/{rid}_water.png",
            "changeOverlay": None,
            "polarization": L["term"], "frequency": L["frequency"],
            "units": "dB (10·log10 of linear backscatter)",
            "grid": encode_grid(db_small, *DB_GRID_RANGE),
            "stats": {**stats, "thresholdDb": DEFAULT_WATER_THRESHOLD_DB, "percentChanged": None, "meanChangeDb": None},
        })
        rec["processing"].update({"outputPixels": list(dims), "outputBytes": size + wsize,
                                  "conversion": "linear power → dB (10·log10); values ≤ 0 treated as no data"})
        if prev is not None:
            # --- Change detection: Δσ = σ_after(dB) − σ_before(dB), pixel by pixel on the shared grid.
            diff = db - prev["db"]
            ok = np.isfinite(diff)
            if ok.sum() > 0:
                d = diff[ok]
                csize, _ = save_png(ramp(diff, -6, 6, DIVERGING), OUT_DIR / f"{rid}_change.png")
                counts, _ = np.histogram(np.clip(d, HIST_EDGES[0], HIST_EDGES[-1]), bins=HIST_EDGES)
                px = pixel_area_km2(grid, bounds)
                both = np.isfinite(db) & np.isfinite(prev["db"])
                w_before = both & (prev["db"] < DEFAULT_WATER_THRESHOLD_DB)
                w_after = both & (db < DEFAULT_WATER_THRESHOLD_DB)
                d0, d1 = parse_date(prev["rec"]["datetime"]), parse_date(rec["datetime"])
                rec["changeOverlay"] = f"data/processed/{rid}_change.png"
                rec["previousId"] = prev["rec"]["id"]
                rec["stats"].update({
                    "meanChangeDb": round_or_none(d.mean(), 3),
                    "percentChanged": round_or_none(100 * (np.abs(d) >= CHANGE_THRESHOLD_DB).sum() / d.size, 2),
                    "changedAreaKm2": round_or_none((np.abs(d) >= CHANGE_THRESHOLD_DB).sum() * px, 1),
                    "changeThresholdDb": CHANGE_THRESHOLD_DB,
                    "overlapPixels": int(d.size),
                    "waterBeforePercent": round_or_none(100 * w_before.sum() / both.sum(), 2),
                    "waterAfterPercent": round_or_none(100 * w_after.sum() / both.sum(), 2),
                    "waterAreaChangeKm2": round_or_none((w_after.sum() - w_before.sum()) * px, 1),
                    "intervalDays": round_or_none((d1 - d0).total_seconds() / 86400, 1),
                    "histogram": {"edgesDb": HIST_EDGES, "counts": [int(c) for c in counts],
                                  "note": "values beyond ±15 dB are counted in the outermost bins"},
                })
                rec["processing"]["outputBytes"] += csize
        prev = {"db": db, "rec": rec}
        records.append(rec)
    return records


def process_single(it, site_id, idx):
    """GUNW / GOFF: one file already represents a change between two dates."""
    import numpy as np
    L = it["layer"]
    grid = web_grid_for([L], OVERLAY_MAX_DIM)
    small = web_grid_for([L], GRID_MAX_DIM)
    bounds = latlon_bounds(grid)
    rid = f"{site_id}-{it['product'].lower()}-{idx + 1}"
    rec = base_record(it, rid, site_id, bounds)
    vals = reproject_to(L, grid)
    ok = np.isfinite(vals)
    if not ok.any():
        raise UnsupportedFile("layer contains no valid pixels after reprojection", [L["path"]], ["finite values"])
    v = vals[ok]
    units = L.get("units") or "units not stated in file"
    if it["product"] == "GUNW":
        lim = float(np.nanpercentile(np.abs(v), 98)) or 1.0
        size, dims = save_png(ramp(vals, -lim, lim, DIVERGING), OUT_DIR / f"{rid}_deformation.png")
        stats = {"minPhase": round_or_none(v.min(), 3), "maxPhase": round_or_none(v.max(), 3),
                 "meanPhase": round_or_none(v.mean(), 3), "phaseUnits": units, "legendRange": [-lim, lim]}
        if L.get("wavelength"):
            los = -L["wavelength"] * v / (4 * math.pi)
            stats.update({"minDisplacement": round_or_none(los.min(), 4), "maxDisplacement": round_or_none(los.max(), 4),
                          "meanDisplacement": round_or_none(los.mean(), 4), "displacementUnits": "m (line of sight, relative)",
                          "wavelengthM": round_or_none(L["wavelength"], 5),
                          "displacementMethod": "d = −λ·φ/(4π); relative to an arbitrary reference; sign convention not verified by EchoSphere"})
        rec.update({"motionKind": "Unwrapped interferometric phase (line-of-sight change between two dates)"})
        grid_vals = reproject_to(L, small)
        rec["grid"] = encode_grid(grid_vals, -lim, lim)
    else:
        lim = float(np.nanpercentile(v, 98)) or 1.0
        size, dims = save_png(ramp(vals, 0, lim, MAGNITUDE), OUT_DIR / f"{rid}_motion.png")
        along = reproject_to(L, grid, L["along"])
        rng = reproject_to(L, grid, L["range"])
        stats = {"minDisplacement": round_or_none(v.min(), 3), "maxDisplacement": round_or_none(v.max(), 3),
                 "meanDisplacement": round_or_none(v.mean(), 3), "displacementUnits": units,
                 "meanAlongTrack": round_or_none(np.nanmean(along), 3), "meanSlantRange": round_or_none(np.nanmean(rng), 3),
                 "direction": "Radar geometry only (along-track / slant-range); geographic direction not derived",
                 "legendRange": [0, lim]}
        rec.update({"motionKind": "Pixel-offset magnitude (displacement between two dates — NOT velocity)"})
        rec["grid"] = encode_grid(reproject_to(L, small), 0, lim)
    d0, d1 = parse_date(it["acq"].get("referenceDatetime")), parse_date(it["acq"].get("secondaryDatetime"))
    if d0 and d1:
        stats["intervalDays"] = round_or_none((d1 - d0).total_seconds() / 86400, 1)
    stats["validPixels"] = int(ok.sum())
    stats["analyzedAreaKm2"] = round_or_none(ok.sum() * pixel_area_km2(grid, bounds), 1)
    rec.update({"overlay": None, "changeOverlay": None, "motionOverlay": f"data/processed/{rec['id']}_{'deformation' if it['product'] == 'GUNW' else 'motion'}.png",
                "units": units, "stats": stats})
    rec["processing"].update({"outputPixels": list(dims), "outputBytes": size})
    return rec


def base_record(it, rid, site_id, bounds):
    L = it["layer"]
    dtm = it["acq"]["datetime"]
    return {
        "id": rid, "site": site_id, "provenance": "REAL NISAR",
        "name": f"NISAR {it['product']} · {(bounds[0][0] + bounds[1][0]) / 2:.3f}°, {(bounds[0][1] + bounds[1][1]) / 2:.3f}°",
        "bounds": bounds, "date": dtm[:10], "datetime": dtm, "dateSource": f"identification/{it['acq']['dateSource']}",
        "referenceDatetime": it["acq"].get("referenceDatetime"), "secondaryDatetime": it["acq"].get("secondaryDatetime"),
        "product": it["product"], "declaredProductType": it["declaredProductType"], "band": it["band"],
        "maturity": it["maturity"], "maturitySource": it["maturitySource"],
        "granule": it["granule"], "granuleSource": it["granuleSource"],
        "sourceFile": it["file"],
        "processing": {
            "dataset": "/" + L["path"], "nativeShape": L["nativeShape"], "nativeSpacing": L["nativeSpacing"],
            "sourceEpsg": L["epsg"], "outputProjection": "EPSG:3857 (Web Mercator, for Leaflet)",
            "readStride": L["readStep"], "resampling": "average",
            "noData": (f"_FillValue={L['fill']}" if L["fill"] is not None else "non-finite values") + (f"; validity mask {L['maskApplied']}" if L.get("maskApplied") else ""),
            "processedAt": _dt.datetime.now(_dt.timezone.utc).isoformat(timespec="seconds"),
        },
    }


def assign_sites(items):
    """Group observations that cover roughly the same place (bounding-box overlap)."""
    from rasterio.transform import array_bounds
    from rasterio.warp import transform_bounds
    for it in items:
        h, w = it["layer"]["data"].shape
        l, b, r, t = array_bounds(h, w, it["layer"]["transform"])
        it["ll"] = transform_bounds(f"EPSG:{it['layer']['epsg']}", "EPSG:4326", l, b, r, t)
    sites = []
    for it in items:
        for s in sites:
            a, c = it["ll"], s["ll"]
            ix = max(0, min(a[2], c[2]) - max(a[0], c[0])) * max(0, min(a[3], c[3]) - max(a[1], c[1]))
            smaller = min((a[2] - a[0]) * (a[3] - a[1]), (c[2] - c[0]) * (c[3] - c[1]))
            if smaller > 0 and ix / smaller > 0.3:
                s["items"].append(it)
                break
        else:
            sites.append({"ll": it["ll"], "items": [it]})
    return sites


# ==========================================================================
# 6. Main
# ==========================================================================
def main():
    log("EchoSphere NISAR processor")
    log(f"  raw data : {RAW_DIR}")
    RAW_DIR.mkdir(parents=True, exist_ok=True)
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    files = sorted(p for p in RAW_DIR.iterdir() if p.suffix.lower() in (".h5", ".hdf5", ".he5"))
    info = {"generatedAt": _dt.datetime.now(_dt.timezone.utc).isoformat(timespec="seconds"),
            "filesFound": [p.name for p in files], "processed": [], "failed": []}

    if not files:
        write_manifest([], info)
        log("  No .h5 files in data/raw/ — nothing to process.")
        log("PASS")
        log("Empty manifest generated.")
        return 0

    try:
        import h5py, numpy, rasterio, pyproj, PIL  # noqa: F401  (check once, clearly)
    except ImportError as exc:
        log(f"ERROR: missing dependency ({exc}). Run:  pip install -r requirements.txt")
        return 1

    # Remove overlays from a previous run so the folder matches the new manifest.
    for old in OUT_DIR.glob("*.png"):
        old.unlink()

    loaded = []
    for p in files:
        log(f"\n→ {p.name}")
        try:
            it = load_file(p)
            log(f"  product {it['product']} ({it['band']}), acquired {it['acq']['datetime']}, dataset /{it['layer']['path']}")
            loaded.append(it)
        except UnsupportedFile as exc:
            fail(info, p.name, exc)
        except (OSError, ValueError, KeyError) as exc:   # corrupt / non-HDF5 / unexpected layout
            fail(info, p.name, UnsupportedFile(f"{type(exc).__name__}: {exc}", [], ["readable NISAR L2 HDF5"]))

    records = []
    for n, site in enumerate(assign_sites(loaded) if loaded else [], start=1):
        site_id = f"nisar-site-{n}"
        gcov = [it for it in site["items"] if it["product"] == "GCOV"]
        # Only same frequency + polarisation observations are compared with each other.
        by_key = {}
        for it in gcov:
            by_key.setdefault((it["layer"]["frequency"], it["layer"]["term"]), []).append(it)
        for key, group in by_key.items():
            try:
                records += process_gcov_group(group, f"{site_id}-{key[1].lower()}" if len(by_key) > 1 else site_id)
                info["processed"] += [g["file"] for g in group]
            except (UnsupportedFile, ValueError, MemoryError) as exc:
                for g in group:
                    fail(info, g["file"], exc if isinstance(exc, UnsupportedFile) else UnsupportedFile(str(exc)))
        others = [it for it in site["items"] if it["product"] != "GCOV"]
        for i, it in enumerate(sorted(others, key=lambda x: parse_date(x["acq"]["datetime"]))):
            try:
                records.append(process_single(it, site_id, i))
                info["processed"].append(it["file"])
            except (UnsupportedFile, ValueError, MemoryError) as exc:
                fail(info, it["file"], exc if isinstance(exc, UnsupportedFile) else UnsupportedFile(str(exc)))

    for png in OUT_DIR.glob("*.png"):
        assert png.stat().st_size < MAX_PNG_BYTES, f"{png.name} exceeds 1 MB"
    write_manifest(records, info)
    log(f"\nSummary: {len(info['processed'])} file(s) processed, {len(info['failed'])} failed, {len(records)} record(s).")
    log(f"Manifest written to {MANIFEST_PATH.relative_to(ROOT)}")
    log("PASS" if records else "PARTIAL — no usable records; the website will show DEMO data.")
    return 0


def fail(info, name, exc):
    log(f"  ✗ SKIPPED {name}: {exc}")
    if getattr(exc, "found", None):
        log("    found:    " + "\n              ".join(map(str, exc.found)))
    if getattr(exc, "expected", None):
        log("    expected: " + "\n              ".join(map(str, exc.expected)))
    info["failed"].append({"file": name, "reason": str(exc)})


if __name__ == "__main__":
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")  # Windows consoles default to cp1252
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        sys.exit(130)
    except Exception:   # last-resort: print the full traceback so it can be reported, then exit non-zero
        traceback.print_exc()
        sys.exit(1)
